/*
    MarXet v2.0
    Written by WolfkillArcadia
    CC BY-NC-SA 4.0
*/
private ['_code', '_function', '_file'];

{
    _code = '';
    _function = _x select 0;
    _file = _x select 1;

    if (isText (missionConfigFile >> 'CfgExileCustomCode' >> _function)) then
    {
        _file = getText (missionConfigFile >> 'CfgExileCustomCode' >> _function);
    };

    _code = compileFinal (preprocessFileLineNumbers _file);

    missionNamespace setVariable [_function, _code];
}
forEach
[
	['ExileClient_marxet_gui_onInventorySelected', 'marxet_server\code\ExileClient_marxet_gui_onInventorySelected.sqf'],
	['ExileClient_marxet_gui_onLoad', 'marxet_server\code\ExileClient_marxet_gui_onLoad.sqf'],
	['ExileClient_marxet_gui_onPanelSwitch', 'marxet_server\code\ExileClient_marxet_gui_onPanelSwitch.sqf'],
	['ExileClient_marxet_gui_onPoptabChar', 'marxet_server\code\ExileClient_marxet_gui_onPoptabChar.sqf'],
	['ExileClient_marxet_gui_onPoptabKeyDown', 'marxet_server\code\ExileClient_marxet_gui_onPoptabKeyDown.sqf'],
	['ExileClient_marxet_gui_onUnload', 'marxet_server\code\ExileClient_marxet_gui_onUnload.sqf'],
	['ExileClient_marxet_gui_toggleSideBar', 'marxet_server\code\ExileClient_marxet_gui_toggleSideBar.sqf'],
	['ExileClient_marxet_gui_updateInventoryDropdown', 'marxet_server\code\ExileClient_marxet_gui_updateInventoryDropdown.sqf'],
	['ExileClient_marxet_gui_updateInventoryListBox', 'marxet_server\code\ExileClient_marxet_gui_updateInventoryListBox.sqf'],
	['ExileClient_marxet_gui_updatePlayerMoney', 'marxet_server\code\ExileClient_marxet_gui_updatePlayerMoney.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onCreateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onCreateButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onPriceChar', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onPriceChar.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onPriceKeyDown', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onPriceKeyDown.sqf'],
	['ExileClient_marxet_gui_auctionCreate_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_postInit.sqf'],
	['ExileClient_marxet_gui_auctionCreate_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_preInit.sqf'],
	['ExileClient_marxet_gui_auctionCreate_toggleItemInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_toggleItemInfo.sqf'],
	['ExileClient_marxet_gui_auctionCreate_updateItemStats', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_updateItemStats.sqf'],
	['ExileClient_marxet_gui_auctionMine_onDeleteButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_onDeleteButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionMine_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_postInit.sqf'],
	['ExileClient_marxet_gui_auctionMine_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_preInit.sqf'],
	['ExileClient_marxet_gui_auctionMine_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_auctionMine_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_auctionMine_thread_updateTimeLeft', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_thread_updateTimeLeft.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidChar', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidChar.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidKeyDown', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidKeyDown.sqf'],
	['ExileClient_marxet_gui_auctionView_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionView_postInit.sqf'],
	['ExileClient_marxet_gui_auctionView_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionView_preInit.sqf'],
	['ExileClient_marxet_gui_auctionView_sortListings', 'marxet_server\code\ExileClient_marxet_gui_auctionView_sortListings.sqf'],
	['ExileClient_marxet_gui_auctionView_toggleItemInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionView_toggleItemInfo.sqf'],
	['ExileClient_marxet_gui_auctionView_updateItemStats', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateItemStats.sqf'],
	['ExileClient_marxet_gui_auctionView_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_auctionView_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_auctionView_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_update', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_update.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_updateBidding', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_updateBidding.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_updateTimeLeft', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_updateTimeLeft.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onAddButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onAddButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onCreateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onCreateButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onItemSelected', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onItemSelected.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onQuantityChar', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onQuantityChar.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onQuantityKeyDown', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onQuantityKeyDown.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onRemoveButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onRemoveButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_postInit.sqf'],
	['ExileClient_marxet_gui_tradeCreate_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_preInit.sqf'],
	['ExileClient_marxet_gui_tradeCreate_updateAvailableListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_updateAvailableListbox.sqf'],
	['ExileClient_marxet_gui_tradeCreate_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_tradeMine_onCloseEditButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onCloseEditButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onDeleteButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onDeleteButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onEditButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onEditButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onUpdateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onUpdateButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_postInit.sqf'],
	['ExileClient_marxet_gui_tradeMine_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_preInit.sqf'],
	['ExileClient_marxet_gui_tradeMine_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_tradeMine_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_tradeView_onPincodeChar', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onPincodeChar.sqf'],
	['ExileClient_marxet_gui_tradeView_onPincodeKeyDown', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onPincodeKeyDown.sqf'],
	['ExileClient_marxet_gui_tradeView_onTradeButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onTradeButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeView_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeView_postInit.sqf'],
	['ExileClient_marxet_gui_tradeView_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeView_preInit.sqf'],
	['ExileClient_marxet_gui_tradeView_sortListings', 'marxet_server\code\ExileClient_marxet_gui_tradeView_sortListings.sqf'],
	['ExileClient_marxet_gui_tradeView_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_tradeView_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_tradeView_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_tradeView_thread_update', 'marxet_server\code\ExileClient_marxet_gui_tradeView_thread_update.sqf'],
	['ExileClient_marxet_system_network_bidResponse', 'marxet_server\code\ExileClient_marxet_system_network_bidResponse.sqf'],
	['ExileClient_marxet_system_network_createListingResponse', 'marxet_server\code\ExileClient_marxet_system_network_createListingResponse.sqf'],
	['ExileClient_marxet_system_network_createTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_createTradeResponse.sqf'],
	['ExileClient_marxet_system_network_deleteListingResponse', 'marxet_server\code\ExileClient_marxet_system_network_deleteListingResponse.sqf'],
	['ExileClient_marxet_system_network_deleteTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_deleteTradeResponse.sqf'],
	['ExileClient_marxet_system_network_editTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_editTradeResponse.sqf'],
	['ExileClient_marxet_system_network_tradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_tradeResponse.sqf'],
	['ExileClient_marxet_system_network_updateRespect', 'marxet_server\code\ExileClient_marxet_system_network_updateRespect.sqf'],
	['ExileClient_marxet_system_process_preInit', 'marxet_server\code\ExileClient_marxet_system_process_preInit.sqf'],
	['ExileClient_marxet_util_array_formatPretty', 'marxet_server\code\ExileClient_marxet_util_array_formatPretty.sqf'],
	['ExileClient_marxet_util_config_getSubClasses', 'marxet_server\code\ExileClient_marxet_util_config_getSubClasses.sqf'],
	['ExileClient_marxet_util_item_getMainStats', 'marxet_server\code\ExileClient_marxet_util_item_getMainStats.sqf'],
	['ExileClient_marxet_util_time_convert', 'marxet_server\code\ExileClient_marxet_util_time_convert.sqf'],
	['ExileClient_marxet_util_time_format', 'marxet_server\code\ExileClient_marxet_util_time_format.sqf'],
	['ExileClient_marxet_util_time_pretty', 'marxet_server\code\ExileClient_marxet_util_time_pretty.sqf'],
	['ExileClient_marxet_util_time_sync', 'marxet_server\code\ExileClient_marxet_util_time_sync.sqf'],
	['ExileClient_marxet_util_vehicle_getOverallDamage', 'marxet_server\code\ExileClient_marxet_util_vehicle_getOverallDamage.sqf'],
	['ExileClient_marxet_util_vehicle_getSkinName', 'marxet_server\code\ExileClient_marxet_util_vehicle_getSkinName.sqf']
];


MarXetClientFunctions = [];
{
	MarXetClientFunctions pushBack [_x select 0, preprocessFileLineNumbers (_x select 1)];
}
forEach [
	['ExileClient_marxet_gui_onInventorySelected', 'marxet_server\code\ExileClient_marxet_gui_onInventorySelected.sqf'],
	['ExileClient_marxet_gui_onLoad', 'marxet_server\code\ExileClient_marxet_gui_onLoad.sqf'],
	['ExileClient_marxet_gui_onPanelSwitch', 'marxet_server\code\ExileClient_marxet_gui_onPanelSwitch.sqf'],
	['ExileClient_marxet_gui_onPoptabChar', 'marxet_server\code\ExileClient_marxet_gui_onPoptabChar.sqf'],
	['ExileClient_marxet_gui_onPoptabKeyDown', 'marxet_server\code\ExileClient_marxet_gui_onPoptabKeyDown.sqf'],
	['ExileClient_marxet_gui_onUnload', 'marxet_server\code\ExileClient_marxet_gui_onUnload.sqf'],
	['ExileClient_marxet_gui_toggleSideBar', 'marxet_server\code\ExileClient_marxet_gui_toggleSideBar.sqf'],
	['ExileClient_marxet_gui_updateInventoryDropdown', 'marxet_server\code\ExileClient_marxet_gui_updateInventoryDropdown.sqf'],
	['ExileClient_marxet_gui_updateInventoryListBox', 'marxet_server\code\ExileClient_marxet_gui_updateInventoryListBox.sqf'],
	['ExileClient_marxet_gui_updatePlayerMoney', 'marxet_server\code\ExileClient_marxet_gui_updatePlayerMoney.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onCreateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onCreateButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onPriceChar', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onPriceChar.sqf'],
	['ExileClient_marxet_gui_auctionCreate_onPriceKeyDown', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_onPriceKeyDown.sqf'],
	['ExileClient_marxet_gui_auctionCreate_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_postInit.sqf'],
	['ExileClient_marxet_gui_auctionCreate_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_preInit.sqf'],
	['ExileClient_marxet_gui_auctionCreate_toggleItemInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_toggleItemInfo.sqf'],
	['ExileClient_marxet_gui_auctionCreate_updateItemStats', 'marxet_server\code\ExileClient_marxet_gui_auctionCreate_updateItemStats.sqf'],
	['ExileClient_marxet_gui_auctionMine_onDeleteButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_onDeleteButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionMine_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_postInit.sqf'],
	['ExileClient_marxet_gui_auctionMine_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_preInit.sqf'],
	['ExileClient_marxet_gui_auctionMine_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_auctionMine_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_auctionMine_thread_updateTimeLeft', 'marxet_server\code\ExileClient_marxet_gui_auctionMine_thread_updateTimeLeft.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidButtonClick', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidButtonClick.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidChar', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidChar.sqf'],
	['ExileClient_marxet_gui_auctionView_onBidKeyDown', 'marxet_server\code\ExileClient_marxet_gui_auctionView_onBidKeyDown.sqf'],
	['ExileClient_marxet_gui_auctionView_postInit', 'marxet_server\code\ExileClient_marxet_gui_auctionView_postInit.sqf'],
	['ExileClient_marxet_gui_auctionView_preInit', 'marxet_server\code\ExileClient_marxet_gui_auctionView_preInit.sqf'],
	['ExileClient_marxet_gui_auctionView_sortListings', 'marxet_server\code\ExileClient_marxet_gui_auctionView_sortListings.sqf'],
	['ExileClient_marxet_gui_auctionView_toggleItemInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionView_toggleItemInfo.sqf'],
	['ExileClient_marxet_gui_auctionView_updateItemStats', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateItemStats.sqf'],
	['ExileClient_marxet_gui_auctionView_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_auctionView_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_auctionView_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_auctionView_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_update', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_update.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_updateBidding', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_updateBidding.sqf'],
	['ExileClient_marxet_gui_auctionView_thread_updateTimeLeft', 'marxet_server\code\ExileClient_marxet_gui_auctionView_thread_updateTimeLeft.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onAddButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onAddButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onCreateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onCreateButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onItemSelected', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onItemSelected.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onQuantityChar', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onQuantityChar.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onQuantityKeyDown', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onQuantityKeyDown.sqf'],
	['ExileClient_marxet_gui_tradeCreate_onRemoveButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_onRemoveButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeCreate_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_postInit.sqf'],
	['ExileClient_marxet_gui_tradeCreate_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_preInit.sqf'],
	['ExileClient_marxet_gui_tradeCreate_updateAvailableListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_updateAvailableListbox.sqf'],
	['ExileClient_marxet_gui_tradeCreate_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_tradeCreate_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_tradeMine_onCloseEditButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onCloseEditButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onDeleteButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onDeleteButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onEditButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onEditButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_onUpdateButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_onUpdateButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeMine_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_postInit.sqf'],
	['ExileClient_marxet_gui_tradeMine_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_preInit.sqf'],
	['ExileClient_marxet_gui_tradeMine_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_tradeMine_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeMine_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_tradeView_onPincodeChar', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onPincodeChar.sqf'],
	['ExileClient_marxet_gui_tradeView_onPincodeKeyDown', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onPincodeKeyDown.sqf'],
	['ExileClient_marxet_gui_tradeView_onTradeButtonClick', 'marxet_server\code\ExileClient_marxet_gui_tradeView_onTradeButtonClick.sqf'],
	['ExileClient_marxet_gui_tradeView_postInit', 'marxet_server\code\ExileClient_marxet_gui_tradeView_postInit.sqf'],
	['ExileClient_marxet_gui_tradeView_preInit', 'marxet_server\code\ExileClient_marxet_gui_tradeView_preInit.sqf'],
	['ExileClient_marxet_gui_tradeView_sortListings', 'marxet_server\code\ExileClient_marxet_gui_tradeView_sortListings.sqf'],
	['ExileClient_marxet_gui_tradeView_updateListingInfo', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateListingInfo.sqf'],
	['ExileClient_marxet_gui_tradeView_updateListingListbox', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateListingListbox.sqf'],
	['ExileClient_marxet_gui_tradeView_updateSortingDropdown', 'marxet_server\code\ExileClient_marxet_gui_tradeView_updateSortingDropdown.sqf'],
	['ExileClient_marxet_gui_tradeView_thread_update', 'marxet_server\code\ExileClient_marxet_gui_tradeView_thread_update.sqf'],
	['ExileClient_marxet_system_network_bidResponse', 'marxet_server\code\ExileClient_marxet_system_network_bidResponse.sqf'],
	['ExileClient_marxet_system_network_createListingResponse', 'marxet_server\code\ExileClient_marxet_system_network_createListingResponse.sqf'],
	['ExileClient_marxet_system_network_createTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_createTradeResponse.sqf'],
	['ExileClient_marxet_system_network_deleteListingResponse', 'marxet_server\code\ExileClient_marxet_system_network_deleteListingResponse.sqf'],
	['ExileClient_marxet_system_network_deleteTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_deleteTradeResponse.sqf'],
	['ExileClient_marxet_system_network_editTradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_editTradeResponse.sqf'],
	['ExileClient_marxet_system_network_tradeResponse', 'marxet_server\code\ExileClient_marxet_system_network_tradeResponse.sqf'],
	['ExileClient_marxet_system_network_updateRespect', 'marxet_server\code\ExileClient_marxet_system_network_updateRespect.sqf'],
	['ExileClient_marxet_system_process_preInit', 'marxet_server\code\ExileClient_marxet_system_process_preInit.sqf'],
	['ExileClient_marxet_util_array_formatPretty', 'marxet_server\code\ExileClient_marxet_util_array_formatPretty.sqf'],
	['ExileClient_marxet_util_config_getSubClasses', 'marxet_server\code\ExileClient_marxet_util_config_getSubClasses.sqf'],
	['ExileClient_marxet_util_item_getMainStats', 'marxet_server\code\ExileClient_marxet_util_item_getMainStats.sqf'],
	['ExileClient_marxet_util_time_convert', 'marxet_server\code\ExileClient_marxet_util_time_convert.sqf'],
	['ExileClient_marxet_util_time_format', 'marxet_server\code\ExileClient_marxet_util_time_format.sqf'],
	['ExileClient_marxet_util_time_pretty', 'marxet_server\code\ExileClient_marxet_util_time_pretty.sqf'],
	['ExileClient_marxet_util_time_sync', 'marxet_server\code\ExileClient_marxet_util_time_sync.sqf'],
	['ExileClient_marxet_util_vehicle_getOverallDamage', 'marxet_server\code\ExileClient_marxet_util_vehicle_getOverallDamage.sqf'],
	['ExileClient_marxet_util_vehicle_getSkinName', 'marxet_server\code\ExileClient_marxet_util_vehicle_getSkinName.sqf']
];
